name: My First Workflow

on: push

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print name
        run: |
          echo "Hello, Yash"
          echo "Welcome to GitHub Actions 🚀"