name: Real CI Workflow (No PR)

on:
  push:
    branches:
      - main

jobs:

  lint-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Lint Check
        run: npm run lint


  test-check:
    runs-on: ubuntu-latest
    needs: lint-check

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Test
        run: npm test


  build-check:
    runs-on: ubuntu-latest
    needs: test-check

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Code
        run: npm run build